development:
  adapter: postgresql
  encoding: unicode
  database: mapster_dev
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: mapster_dev
  pool: 5
  host: localhost

default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
