development:
  adapter: postgresql
  encoding: unicode
  database: mapster_dev
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: mapster_dev
  pool: 5
  host: localhost

